name = "Vanilla Latte"
author = "James Laverack"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58ee4ca9a7a75969a99cd59bf51bae9909b96c0a3e6b031016173fc11f68fcb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
