name = "Vanilla Latte"
author = "James Laverack"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "717706f27e826ca702da8c664eb5ebff2727ccebf960e08c7096d44e563d83af"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
