name = "Vanilla Latte"
author = "James Laverack"
version = "1.21-latte.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9e9ed9b88067b1338977a5503bdfd8fc6a4555ce0f1cfcb61107887f31dd602"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
