name = "Vanilla Latte"
author = "James Laverack"
version = "1.20.6-latte.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "128f38e020ad993c51dc85309996f4b8c8066dc9dd000b33a005ea4c4e19b70d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
