name = "Vanilla Latte"
author = "James Laverack"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f1c1eac63aa13ee18bf123085f8268a9c88998bd8e5c7232fa77c57a1482a69"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
